[package]
name = "raytracer"
version = "0.1.0"
authors = ["Kolaer <overlordin777@gmail.com>", "s3rius <win10@list.ru>", "ussr-jesus <groundhog448@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21" # https://docs.rs/image/0.21.0/image/
rayon = "1.0" # https://docs.rs/rayon/1.0.3/rayon/

